# Generated by Django 3.2.4 on 2022-04-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('laUrl', models.CharField(max_length=100)),
                ('grupPermis', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'aplicacio',
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('tipus', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RefCapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codiCapa', models.CharField(max_length=100)),
                ('nomCapa', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('tipus', models.CharField(max_length=200)),
                ('matrixSet', models.CharField(max_length=30, null=True)),
                ('format', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codiMapa', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=200)),
                ('tipus', models.CharField(max_length=20)),
                ('descripcio', models.TextField(null=True)),
                ('pUrl', models.CharField(max_length=200, null=True)),
                ('urlCapabilities', models.CharField(default='X', max_length=200, null=True)),
                ('matrixSet', models.CharField(max_length=30, null=True)),
                ('format', models.CharField(max_length=20, null=True)),
                ('foto', models.ImageField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('mapa_actual', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RefMapaCapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codiMapa', models.CharField(max_length=5)),
                ('codiCapa', models.CharField(max_length=5)),
            ],
        ),
    ]
