# Generated by Django 3.2.4 on 2022-03-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QVCataleg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refmapawms',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='refmapawms',
            name='updated_at',
        ),
    ]
