# Generated by Django 3.2.4 on 2022-05-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QVCataleg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refmapa',
            name='mapa_compost',
            field=models.BooleanField(default=False),
        ),
    ]
