# Generated by Django 3.2.4 on 2022-03-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QVCataleg', '0002_auto_20220330_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='refmapawms',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='refmapawms',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
