# Generated by Django 3.2.4 on 2022-04-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QVCataleg', '0003_auto_20220330_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='refmapawms',
            name='format',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
