# Generated by Django 3.2.4 on 2022-04-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QVCataleg', '0005_refmapawms_mapa_actual'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefCapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codiCapa', models.CharField(max_length=5)),
                ('nomCapa', models.CharField(max_length=200)),
                ('nomCapaNormalitzada', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('tipus', models.CharField(max_length=200)),
                ('matrixSet', models.CharField(max_length=30, null=True)),
                ('format', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codiMapa', models.CharField(max_length=5)),
                ('nomMapa', models.CharField(max_length=200)),
                ('metaMapa', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefMapaCapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codiMapa', models.CharField(max_length=5)),
                ('codiCapa', models.CharField(max_length=5)),
            ],
        ),
    ]
