# Generated by Django 3.2.4 on 2022-04-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QVCataleg', '0006_refcapa_refmapa_refmapacapa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refcapa',
            name='nomCapaNormalitzada',
        ),
    ]
