# Generated by Django 3.2.4 on 2022-04-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QVCataleg', '0008_remove_refmapawms_pcapes'),
    ]

    operations = [
        migrations.AddField(
            model_name='refmapawms',
            name='descripcio',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
