# Generated by Django 3.2.4 on 2022-04-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QVCataleg', '0009_refmapawms_descripcio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refmapa',
            name='codiMapa',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='refmapawms',
            name='descripcio',
            field=models.TextField(null=True),
        ),
    ]
