# Generated by Django 3.2.4 on 2022-04-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QVCataleg', '0010_auto_20220425_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refmapa',
            name='codiMapa',
            field=models.CharField(max_length=5),
        ),
    ]
