# Generated by Django 3.2.4 on 2022-04-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QVCataleg', '0011_alter_refmapa_codimapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refcapa',
            name='codiCapa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='refmapa',
            name='codiMapa',
            field=models.CharField(max_length=100),
        ),
    ]
